# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'version.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("#MainWindow{\n"
"    border:none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("#frame{\n"
"    background-color:rgb(224, 254, 255);\n"
"    border:none;\n"
"}\n"
"QFrame{\n"
"    border:none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    \n"
"    background-image: url(./designer/2.png);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(940, 10, 111, 31))
        self.frame_5.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgba(8, 0, 255,0);\n"
"    border:none;\n"
"    border-radius:11px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setGeometry(QtCore.QRect(60, 0, 31, 28))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./designer/times-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 0, 31, 28))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./designer/compress-alt-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 15, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("#label{\n"
"    color: white;\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("#frame_4{\n"
"    background-image: url(./designer/2.png);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7{\n"
"    background-color:rgb(253, 255, 248)\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:rgb(255, 246, 224);\n"
"    border:2px solid;\n"
"    border-color:rgb(255, 213, 46);\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_11.setGeometry(QtCore.QRect(60, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setMouseTracking(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./designer/upload-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.listWidget = QtWidgets.QListWidget(self.frame_7)
        self.listWidget.setGeometry(QtCore.QRect(10, 50, 191, 541))
        self.listWidget.setStyleSheet("#listWidget{\n"
"    background-color:(255, 255, 255);\n"
"    border:inset;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame_6.setStyleSheet("#frame_6{\n"
"    background-color:rgb(253, 255, 248)\n"
"}\n"
"QStackedWidget{\n"
"    background-color:rgb(253, 255, 248)\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)

        """
        "QStackedWidget{\n"
        "    background-color:rgb(253, 255, 248)\n"
        "}"
        """

        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")

        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")



        self.frame_11 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setStyleSheet("QPushButton{\n"
"    background-color:rgb(255, 246, 224);\n"
"    border:none;\n"
"    border-radius:22px;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./designer/scissors-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.frame_11)
        self.horizontalSlider_3.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_3.setStyleSheet(

                "QSlider::handle:horizontal {\n"
                "    background-color: orange;\n"
                "    border: 2px solid #fff;\n"
                "    width: 10px;\n"
                "    margin-top: -3px;\n"
                "    margin-bottom: -3px;\n"
                "    border-radius: 5px;\n"
                "}\n"
                "QSlider::add-page:horizontal {\n"
                "    background: transparent;\n"
                "}\n"
                "QSlider::sub-page:horizontal {\n"
                "    background: transparent;\n"
                "}\n"
                "QSlider::handle:horizontal:hover {\n"
                "    background-color:rgb(203, 93, 38);\n"
                "}\n"
        )

        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalLayout_7.addWidget(self.horizontalSlider_3)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.frame_11)
        self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_2.setStyleSheet(
                "QSlider::handle:horizontal {\n"
                "    background-color: orange;\n"
                "    border: 2px solid #fff;\n"
                "    width: 10px;\n"
                "    margin-top: -3px;\n"
                "    margin-bottom: -3px;\n"
                "    border-radius: 5px;\n"
                "}\n"
                "QSlider::add-page:horizontal {\n"
                "    background: transparent;\n"
                "}\n"
                "QSlider::sub-page:horizontal {\n"
                "    background: transparent;\n"
                "}\n"
                "QSlider::handle:horizontal:hover {\n"
                "    background-color:rgb(203, 93, 38);\n"
                "}\n")
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_2.setTickInterval(5)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_7.addWidget(self.horizontalSlider_2)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_10.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_10.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./designer/object-ungroup-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_7.addWidget(self.pushButton_10)
        self.verticalLayout_2.addWidget(self.frame_11)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_6.raise_()
        self.frame_7.raise_()
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("#frame_3{\n"
"    background-color:rgb(251, 255, 233)\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setStyleSheet("QPushButton{\n"
"    background-color:rgb(255, 246, 224);\n"
"    border:none;\n"
"    border-radius:22px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_6.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_6.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setMouseTracking(True)
        self.pushButton_6.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./designer/backward-fast-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_5.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_5.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setMouseTracking(True)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    Background-color:rgb(76, 207, 255)\n"
"    border:none;\n"
"    border-radius:22px\n"
"}")
        self.pushButton_5.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./designer/circle-play-regular.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon6)
        self.pushButton_5.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_4.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_4.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setMouseTracking(True)
        self.pushButton_4.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("./designer/forward-fast-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon7)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setStyleSheet("QPushButton{\n"
                                "    border:none;\n"
                                "    border-radius:22px;\n"
                                "}"
                                    "QToolButton{\n"
                                    "    border:none;\n"
                                    "    border-radius:22px;\n"
                                    "}"
                                    )
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalSlider = QtWidgets.QSlider(self.frame_10)
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider.setMouseTracking(True)
        self.horizontalSlider.setStyleSheet("QSlider{\n"
"    height:40px;\n"
"}\n"
"QSlider::groove:horizontal{\n"
"        height: 12px;left: 0px;right: 0px;border:0px;border-radius:6px;background:rgba(0,0,0,20)\n"
"        \n"
"}\n"
"QSlider::handle:horizontal{\n"
"        width:  22px;\n"
"        height: 15px;\n"
"       margin-top: -8px;\n"
"        margin-left: 0px;\n"
"        margin-bottom: -8px;\n"
"        margin-right: 0px;\n"
"    border-image: url(./designer/grin-beam-sweat-solid.svg);\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal{\n"
"       background:rgba(255,236,193,1);\n"
"}\n"
"\n"
"\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_5.addWidget(self.horizontalSlider)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_8.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_8.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setMouseTracking(True)
        self.pushButton_8.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("./designer/volume-high-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon8)
        self.pushButton_8.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_5.addWidget(self.pushButton_8)
        self.toolButton = QtWidgets.QToolButton(self.frame_10)
        self.toolButton.setMinimumSize(QtCore.QSize(45, 45))
        self.toolButton.setMaximumSize(QtCore.QSize(45, 45))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton.setMouseTracking(True)
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.toolButton.setText("")
        icon100 = QtGui.QIcon()
        icon100.addPixmap(QtGui.QPixmap("./designer/gauge-simple-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon100)
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.horizontalLayout_5.addWidget(self.toolButton)
        self.horizontalLayout_3.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setStyleSheet("QPushButton{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius:20px;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_9.setMaximumSize(QtCore.QSize(75, 75))
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setMouseTracking(True)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    Background-color:rgb(255, 246, 224);\n"
"    border:none;\n"
"    border-radius:22px\n"
"}")
        self.pushButton_9.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("./designer/record-vinyl-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon9)
        self.pushButton_9.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Sound Recorder"))
        self.pushButton_11.setText(_translate("MainWindow", " Import File"))

